name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  format:
    name: format & lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Check format
      run: |
        gofmt -l .
    - name: Check lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: latest
    - uses: dprint/check@v1.3
    # - name: Check docs
    #   run: make docscheck
  test:
    name: Unit & Acceptance tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Acceptance Tests
      run: make testacc
      env:
        DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}